### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ShahriarDhruvo** [mnansary/indicparser#1]
Test word: "সম্পর্কে"

<img width="1416" alt="Screenshot 2022-06-14 at 12 24 02 AM" src="https://user-images.githubusercontent.com/42747800/173419832-05bb62d7-403c-48c3-ae34-ad20420a73f0.png">

**Comment by mnansary** [comment]
cant reproduce .... details on word operations please
also please share indicparser version: `(pip freeze | grep indicparser)`
![Screenshot from 2022-06-14 00-41-47](https://user-images.githubusercontent.com/22679832/173422750-61a9637b-d8f7-4fcc-bc72-3476dd6faea1.png)
